/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Nyilonelycompany (https://sketchfab.com/Nyilonelycompany)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/love-birds-parrot-e31e1c72cff140158b99172285b40056
Title: Love Birds Parrot
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import React, { useEffect, useRef } from "react";
import birdPrefab from "../assets/characters/bird.glb";

const Bird = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(birdPrefab);
  const { actions, names } = useAnimations(animations, group);

  useEffect(() => {
    actions[names[0]].reset().fadeIn(0.5).play()
  }, [])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.63}
        >
          <group name="Love_birdsabccleanermaterialmergergles">
            <group name="Object_2" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Object_3" scale={0.01}>
                <group name="Object_4" rotation={[-0.06, 0, 0]} scale={202.35}>
                  <group name="MorphMainGroup">
                    <mesh
                      name="lovebird"
                      castShadow
                      receiveShadow
                      geometry={nodes.lovebird.geometry}
                      material={materials.lovebird}
                      morphTargetDictionary={
                        nodes.lovebird.morphTargetDictionary
                      }
                      morphTargetInfluences={
                        nodes.lovebird.morphTargetInfluences
                      }
                    />
                  </group>
                  <group
                    name="Object_7"
                    rotation={[-0.159, -0.017, -0.039]}
                    scale={[0.025, 0.024, 0.024]}
                  >
                    <group name="MorphMainGroup_1">
                      <mesh
                        name="Love_wings"
                        castShadow
                        receiveShadow
                        geometry={nodes.Love_wings.geometry}
                        material={materials.Love_wings}
                        morphTargetDictionary={
                          nodes.Love_wings.morphTargetDictionary
                        }
                        morphTargetInfluences={
                          nodes.Love_wings.morphTargetInfluences
                        }
                      />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/love_birds_parrot.glb");

export default Bird;
